name: Build Vue
on: push
jobs:
  build-vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "sqweelygig"
          reponame: "supercool-servers"
          token: ${{ secrets.GITHUB_TOKEN }}
